#cloud-config
output: {all: '| tee -a /var/log/cloud-init-output.log'}

package_update: true
package_upgrade: true

packages:
 - git
 - curl
 - wget
 - zsh
 - vim
 - bash-completion
 - pastebinit
 - python3
 - python3-pip
 - apt-transport-https
 - ca-certificates
 - software-properties-common
 - mlocate
 - tree

runcmd:
 - sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
 - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
 - sudo apt-cache policy docker-ce
 - sudo apt install -y docker-ce docker-ce-cli containerd.io
 - sudo usermod -aG docker ubuntu
 - sudo curl -L "https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl
 - sudo chmod +x /usr/local/bin/kubectl
 - curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
 - sudo install minikube-linux-amd64 /usr/local/bin/minikube
 - sudo snap install kustomize
 - sudo snap install helm --classic
 - sudo snap install skaffold
 - sudo pip3 install archey4
 - runuser -l ubuntu -c 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"' 
 - chsh -s $(which zsh) ubuntu
 - echo "source ~/.profile" >> /home/ubuntu/.zshrc
 - echo "archey" >> /home/ubuntu/.zshrc
 - git clone https://github.com/zsh-users/zsh-autosuggestions.git /home/ubuntu/.oh-my-zsh/custom/plugins/zsh-autosuggestions
 - git clone https://github.com/zsh-users/zsh-syntax-highlighting.git /home/ubuntu/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
 - sed -i 's/^plugins=.*/plugins=(git docker zsh-autosuggestions zsh-syntax-highlighting kubectl helm)/g' /home/ubuntu/.zshrc

write_files:
  - path: /etc/netplan/60-bridge.yaml
    content: |
      network:
        ethernets:
          enp0s8:                  
            dhcp4: true
            dhcp4-overrides: 
              route-metric: 200
        version: 2
    owner: root:root
    permissions: '0644'