name: Tag

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest

    outputs:
      new_version: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: GitVersion Setup
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: GitVersion Execute
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

  tag:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Tag
        id: tag
        uses: mathieudutour/github-tag-action@v5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ needs.version.outputs.new_version }}
          release_branches: main
          pre_release_branches: dev

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          release_name: Release ${{ steps.tag.outputs.new_tag }}
          body: ${{ steps.tag.outputs.changelog }}%